/* ============================================
   StartupEvents — Advanced Seed Data Script
   Generated by Antigravity for Data-Driven Testing
   ============================================ */

const mongoose = require('mongoose');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const Event = require('../models/Event');
const User = require('../models/User');
const RSVP = require('../models/RSVP');
const logger = require('../utils/logger');

/**
 * Advanced Seed Settings
 */
const NUM_ATTENDEES = 30; // High user count for reach metrics
const RSVPS_PER_USER_MIN = 3;
const RSVPS_PER_USER_MAX = 8;

const sampleOrganizers = [
  {
    firstName: 'Test',
    lastName: 'Organizer 1',
    email: 'test.organizer1@example.com',
    password: 'Password@123',
    role: 'organizer',
    bio: 'Primary test organizer account.',
  },
  {
    firstName: 'Test 2',
    lastName: 'Organizer',
    email: 'test2.organizer@example.com',
    password: 'Password@123',
    role: 'organizer',
    bio: 'Secondary test organizer account.',
  },
];

const primaryAttendee = {
  firstName: 'Test',
  lastName: 'User',
  email: 'test.user@example.com',
  password: 'Password@123',
  role: 'attendee',
};

const sampleAdmins = [
  {
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@startupevents.com',
    password: 'Admin@123',
    role: 'admin',
  },
];

// Generate dynamic attendees
const generateAttendees = (count) => {
  const attendees = [];
  const firstNames = ['Amit', 'Neha', 'Sanjay', 'Aditi', 'Rahul', 'Sneha', 'Vikram', 'Anjali', 'Deepak', 'Kavita', 'Arjun', 'Isha', 'Rohan', 'Tanvi'];
  const lastNames = ['Singh', 'Patel', 'Kumar', 'Nayar', 'Verma', 'Das', 'Reddy', 'Gupta', 'Iyer', 'Mehta', 'Kaur'];

  for (let i = 0; i < count; i++) {
    const f = firstNames[Math.floor(Math.random() * firstNames.length)];
    const l = lastNames[Math.floor(Math.random() * lastNames.length)];
    attendees.push({
      firstName: f,
      lastName: l,
      email: `${f.toLowerCase()}.${l.toLowerCase()}.${i}@example.com`,
      password: 'Attendee@123',
      role: 'attendee',
    });
  }
  return attendees;
};

const getSampleEvents = (org1, org2) => [
  {
    title: 'Build for Tomorrow — 48hr Hackathon',
    description: 'A 48-hour hackathon bringing together 500+ developers.',
    category: 'hackathon',
    date: new Date('2026-05-15'),
    location: { venue: 'TechHub Bangalore', city: 'Bangalore', country: 'India' },
    organizer: org1,
    capacity: 500,
    tags: ['ai/ml', 'web3'],
    status: 'upcoming',
    isFeatured: true,
  },
  {
    title: 'Startup Pitch Arena — Season 4',
    description: '10 startups pitch to a panel of VCs.',
    category: 'pitch-night',
    date: new Date('2026-05-22'),
    location: { venue: 'Surge HQ', city: 'Delhi', country: 'India' },
    organizer: org2,
    capacity: 200,
    tags: ['funding', 'pitch'],
    status: 'upcoming',
    isFeatured: true,
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'Intensive workshop covering MERN.',
    category: 'workshop',
    date: new Date('2026-06-03'),
    location: { venue: 'WeWork BKC', city: 'Mumbai', country: 'India' },
    organizer: org1,
    capacity: 120,
    tags: ['mern', 'workshop'],
    status: 'upcoming',
  },
  {
    title: 'GreenTech Challenge',
    description: 'Sustainability challenge for innovators.',
    category: 'hackathon',
    date: new Date('2026-06-20'),
    location: { venue: 'IIT Madras', city: 'Chennai', country: 'India' },
    organizer: org2,
    capacity: 300,
    tags: ['sustainability', 'green'],
    status: 'upcoming',
  },
  {
    title: 'Founders Evening Meetup',
    description: 'Monthly coffee and networking.',
    category: 'meetup',
    date: new Date('2026-04-28'),
    location: { venue: 'Blue Tokai', city: 'Bangalore', country: 'India' },
    organizer: org1,
    capacity: 80,
    tags: ['founders', 'networking'],
    status: 'upcoming',
  },
];

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/startupevents';
    await mongoose.connect(mongoUri);
    logger.info('Connected to MongoDB for high-fidelity seeding');

    // 1. Teardown
    await User.deleteMany({});
    await Event.deleteMany({});
    await RSVP.deleteMany({});
    logger.info('Cleaned all existing data');

    // 2. Create Users
    const attendees = await User.create([...generateAttendees(NUM_ATTENDEES), primaryAttendee]);
    const organizers = await User.create(sampleOrganizers);
    const admins = await User.create(sampleAdmins);
    logger.info(`Created ${attendees.length} attendees and ${organizers.length} organizers`);

    // 3. Create Events
    const org1 = organizers.find(o => o.email === 'test.organizer1@example.com')._id;
    const org2 = organizers.find(o => o.email === 'test2.organizer@example.com')._id;
    const events = await Event.create(getSampleEvents(org1, org2));
    logger.info(`Created ${events.length} sample events`);

    // 4. Generate Staggered RSVPs (for Analytics)
    logger.info('Generating time-staggered RSVPs...');
    const rsvpOperations = [];
    const eventUpdates = new Map();

    for (const attendee of attendees) {
      // Pick random number of events for this user
      const count = Math.floor(Math.random() * (RSVPS_PER_USER_MAX - RSVPS_PER_USER_MIN + 1)) + RSVPS_PER_USER_MIN;
      const shuffledEvents = [...events].sort(() => 0.5 - Math.random()).slice(0, count);

      for (const event of shuffledEvents) {
        // Create a fake date within the last 15 days
        const daysAgo = Math.floor(Math.random() * 15); 
        const createdAt = new Date();
        createdAt.setDate(createdAt.getDate() - daysAgo);

        rsvpOperations.push({
          user: attendee._id,
          event: event._id,
          status: 'confirmed',
          createdAt: createdAt,
        });

        // Track attendees for the Event record sync
        if (!eventUpdates.has(event._id.toString())) {
          eventUpdates.set(event._id.toString(), []);
        }
        eventUpdates.get(event._id.toString()).push(attendee._id);
      }
    }

    // Bulk insert RSVPs
    const createdRSVPs = await RSVP.insertMany(rsvpOperations);
    logger.info(`Inserted ${createdRSVPs.length} staggered RSVPs`);

    // 5. Sync Attendees back to Events
    for (const [eventId, attendeeIds] of eventUpdates) {
      await Event.findByIdAndUpdate(eventId, { attendees: attendeeIds });
    }
    logger.info('Synced attendee lists to Event records');

    logger.info('✅ Advanced seed complete!');
    logger.info('--------------------------------');
    logger.info('Test accounts:');
    logger.info('  Organizer 1: test.organizer1@example.com / Password@123');
    logger.info('  Organizer 2: test2.organizer@example.com / Password@123');
    logger.info('  Standard User: test.user@example.com / Password@123');
    logger.info('--------------------------------');

    process.exit(0);
  } catch (error) {
    logger.error(`Advanced Seeding failed: ${error.message}`);
    process.exit(1);
  }
};

seedDatabase();
